version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: curiorserviceapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/curiorserviceapp?schema=public
      PORT: 5000

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: